### ISSUE TITLE
想要加个友链的喵～

### ISSUE THREAD

**Issue by ayalhw** [KiteAB/KiteAB.github.io#1]
喵呜，博客地址在这里：https://blog.lhwcrt.top/
头像可以用这个：https://blog.lhwcrt.top/icon.png

**Comment by KiteAB** [comment]
主题限制  暂时无法添加头像
`[8952631](https://github.com/KiteAB/KiteAB.github.io/commit/89526312a9be80bba92acf1fb7e964394137568a)`

**Comment by KiteAB** [comment]
换了主题
60c1abb

**Comment by ayalhw** [comment]
咱博客换域名了，现在域名是 https://blog.coelacanthus.moe 麻烦更新下
（以前是 https://blog.lhwcrt.top
